create_validation_set_every: 100
data:
  train_batch_size: 8
  train_epoch_size: 256
decrease_lr_every: 400
decrease_lr_times: 2
env:
  num_dice: 1
  num_faces: 1
  random_action_prob: 0.25
  sample_leaf: true
  subgame_params:
    linear_update: true
    max_depth: 2
    num_iters: 1024
    use_cfr: true
exploit: true
grad_clip: 5.0
job_id: adhoc/2025-03-31T17:30:51.520736/c02_selfplay/liars_sp@env.num_dice@1@env.num_faces@1@selfplay.cpu_gen_threads@6@env.subgame_params.use_cfr@true
loss: huber
max_epochs: 100
min_buffer_to_send: 250
model:
  kwargs:
    n_hidden: 256
    n_layers: 2
    use_layer_norm: true
  name: Net2
optimizer:
  classname: Adam
  kwargs:
    lr: 0.0003
replay:
  alpha: 1.0
  beta: 1.0
  capacity: 2000
  prefetch: 8
  use_priority: false
seed: 0
selfplay:
  cpu_gen_threads: 6
  dump_dataset_every_epochs: 200
  models_per_gpu: 1
  network_sync_epochs: 1
  threads_per_gpu: -1
task: selfplay
train_gen_ratio: 4
